### ISSUE TITLE
(●'◡'●)

### ISSUE THREAD

**Issue by lightyears1998** [linyangqi/board_game_is_magic-demo#1]
从 [godoter.cn](https://godoter.cn/d/248-mlp-zhuo-you-shi-mo-fa-godotban-kai-fa-zhong-shi-yong-godot-4) 过来的。我是 Godot 新手一枚，可以提几点不成熟的建议吗。🤣

1. 关于 `*.import` 文件，[官方文档](https://docs.godotengine.org/en/latest/tutorials/assets_pipeline/import_process.html#files-generated)似乎是建议把他们提交到 git 里面的。i.e. 对应素材的 .import 文件如果不存在的话，Godot 会用 默认配置 重新导入素材。如果现在为素材定义了默认导入以外的其他导入方式的话，不提交到 git，其他人 clone 下来就看不到效果了。

2. 可以考虑在 README 里面加上 bilibili 或者 youtube 上介绍开发这个游戏的视频，也许可以帮助其他人快速了解这个项目。

3. 可以考虑启用 GitHub Discussion。（Settings -> Features -> Disussion）~~这样像我这样不请自来的人就可以水贴混脸熟，啊不，应该是~~ 可以不用 issue 打扰到其他人。

Thanks! 这个游戏看上去好有趣，期待后续的开发。（狮狮真的好可爱！）

φ(゜▽゜*)♪

**Comment by linyangqi** [comment]
😂十分感谢建议（个人还有些不熟github）
_(:з」∠)_后面找到时间马上来弄

**Comment by linyangqi** [comment]
非常感谢，现在discussion页面也有了🤣
https://github.com/linyangqi/board_game_is_magic-demo/discussions

（以及.import以及视频链接也都有了）
